language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - 4.0.5
os:
  - linux
# TODO re-enable when dotnet supports OSX 10.9 or travis upgrades its agents
#  - osx
# before_install:
#  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
before_script:
  - sqlite3 -version
script:
  - ./build.sh --quiet verify
