language: csharp
sudo: false
mono:
  - alpha
os:
  - linux

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - libunwind8
    - sqlite3

before_script:
  - sqlite3 -version
script:
  - ./build.sh --quiet verify
